name: Ellen Campbell
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#5a5758'
    - '#7d7a7b'
    - '#b2afb0'
    - '#f3f3f3'
  brandStrength: 1
  lightness: 0.2736104070208967
  saturation: 0.2427711859345436
  rhythmicContrast: 0.1703139254823327
purpose: []
