name: Ellen Campbell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fcff'
    - '#100a0a'
    - '#afb5c2'
    - '#af8382'
    - '#4c2f29'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
