name: Ellen Campbell
favicon: null
layout_spectrum: 0.48948883614502847
typography_spectrum: 0.6405674554407597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5029464561957866
  lightness: 0.2736104070208967
  saturation: 0.2427711859345436
  rhythmicContrast: 0.1703139254823327
purpose: []
